baseurl: http://barretlee.github.io/shares
host: barretlee.github.io
markdown: rdiscount
permalink: /:year/:month/:title/

author: Barret Lee
email: barret.china@gmail.com
author_info: <a href="http://barretlee.com">Barret Lee</a>