baseurl: /
markdown: rdiscount
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai

home: http://www.barretlee.com/
demo: http://demo.barretlee.com/
base: http://snippet.barretlee.com
weibo: http://weibo.com/hustskyking
edit_path: https://github.com/barretlee/snippet/edit/gh-pages/_posts
author: 小胡子哥
author_en: Barret Lee
email: barret.china@gmail.com
author_info: <a href="http://www.barretlee.com">小胡子哥</a>
