<<<<<<< HEAD
baseurl: /shares
=======
baseurl: /
>>>>>>> a53e4f0d04b24803b666ab52000ffa7100430200
markdown: rdiscount
permalink: /:year/:month/:title/


basename: /shares
author: Barret Lee
email: barret.china@gmail.com
author_info: <a href="http://barretlee.com">Barret Lee</a>
