baseurl: /
markdown: rdiscount
permalink: /:year/:month/:title/

edit_path: https://github.com/barretlee/Micro-Share/edit/gh-pages/_posts
author: Barret Lee
email: barret.china@gmail.com
author_info: <a href="http://barretlee.com">Barret Lee</a>
